// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StamAcasa.Common;

namespace StamAcasa.Common.Migrations
{
    [DbContext(typeof(UserDbContext))]
    [Migration("20200404214415_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2");

            modelBuilder.Entity("StamAcasa.Common.Form", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasColumnType("jsonb");

                    b.Property<string>("FormTypeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Forms");
                });

            modelBuilder.Entity("StamAcasa.Common.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("County")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LivesWithOthers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreexistingMedicalCondition")
                        .HasColumnType("TEXT");

                    b.Property<int>("QuarantineStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("QuarantineStatusOthers")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RelationshipType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Smoker")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sub")
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("StamAcasa.Common.Form", b =>
                {
                    b.HasOne("StamAcasa.Common.Models.User", "User")
                        .WithMany("Forms")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StamAcasa.Common.Models.User", b =>
                {
                    b.HasOne("StamAcasa.Common.Models.User", "ParentUser")
                        .WithMany("DependentUsers")
                        .HasForeignKey("ParentId");
                });
#pragma warning restore 612, 618
        }
    }
}
